Algoritmo "semnome"

// Se  o de Declara  es das vari veis
v1: vetor [1..2] de inteiro
   v2: vetor [1..2] de inteiro
   v3: vetor [1..2] de inteiro

Inicio
// Se  o de Comandos, procedimento, funções, operadores, etc ...
 Escreva ("Informe um valor para o 1 vetor:")
   leia (v1 [1])
   Escreva ("Informe um valor para o 2 vetores:")
   leia (v2 [1])
   v3 [1] <- v2 [1] + v1 [1]
   Escreva ("A soma do 1 vetor + 2  vetor e:", v3 [1])

Fimalgoritmo