Algoritmo "semnome"
// Disciplina: [Linguagem e L gica de Programa  o]
// Professor: Antonio Carlos Nicolodi
// Descrição: Aqui voc  alunos o que o programa faz! (fun  o)
// Autor (a): Nome do (a) aluno (a)
// Dados atuais: 11/08/2020
Var
// Se  o de Declara  es das vari veis
   CONTADOR: INTEIRO


Inicio
// Se  o de Comandos, procedimento, funções, operadores, etc ...
 PARA CONTADOR <- 100 ATE 4 PASSO -2 FACA
 ESCREVAL (CONTADOR)
 FIMPARA

Fimalgoritmo