Algoritmo "semnome"
// Disciplina: [Linguagem e L gica de Programa  o]
// Professor: Antonio Carlos Nicolodi
// Descrição: Aqui voc  alunos o que o programa faz! (fun  o)
// Autor (a): Nome do (a) aluno (a)
// Dados atuais: 11/08/2020
Var
// Se  o de Declara  es das vari veis
N1: inteiro


Inicio
// Se  o de Comandos, procedimento, funções, operadores, etc ...
   para N1 de 1 ate 20 passo 1 faca
     escreval ("1 /", N1)
fimpara


Fimalgoritmo