Algoritmo "repeti ao"
// Disciplina: [Linguagem e L gica de Programa  o]
// Professor: Antonio Carlos Nicolodi
// Descrição: Aqui voc  alunos o que o programa faz! (fun  o)
// Autor (a): Nome do (a) aluno (a)
// Dados atuais: 10/08/2020
Var
// Se  o de Declara  es das vari veis
n1: inteiro

Inicio
// Se  o de Comandos, procedimento, funções, operadores, etc ...
 PARA n1 <-1 ate 1000 faca
 ESCREVAL ("PROA 4.0", n1)
 fimpara
Fimalgoritmo